package Arsip_dokumen;

import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author lilissonia
 */
public class UbahData extends javax.swing.JPanel {
    Data arsip;
    String file = null;
    public UbahData(Data d) {
        initComponents();
        
        arsip = d;
       // txtKode.setText(arsip.getkode_dokumen());
        txtNama.setText(arsip.getNama());
        txtKategori.setText(arsip.getKategori());
        txtLokasi.setText(arsip.getLokasi());
        txtDes.setText(arsip.getDeskripsi());
        txtTanggal.setText(arsip.getTanggal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtKategori = new javax.swing.JTextField();
        txtLokasi = new javax.swing.JTextField();
        txtDes = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnUpload = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Dokumen");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Dokumen");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kategori Dokumen");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lokasi Dokumen");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Deskripsi Dokumen");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtTanggal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });
        jPanel2.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 200, -1));

        txtKode.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 200, -1));

        txtNama.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 200, -1));

        txtKategori.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(txtKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 200, -1));

        txtLokasi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(txtLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, -1));

        txtDes.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(txtDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 200, -1));

        btnUbah.setBackground(new java.awt.Color(204, 102, 0));
        btnUbah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel2.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        btnCancel.setBackground(new java.awt.Color(204, 102, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setText("Batal");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 550, 90));

        btnUpload.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String kode = txtKode.getText();
        String nama = txtNama.getText();
        String kategori = txtKategori.getText();
        String lok = txtLokasi.getText();
        String des = txtDes.getText();
        String tgl = txtTanggal.getText();
        
        if(kode.isEmpty()){
            JOptionPane.showMessageDialog(this, "Kode Dokumen Harus diisi");
            txtKode.requestFocus();
        }else if(nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama Dokumen Harus diisi");
          txtNama.requestFocus();
        }else if(kategori.isEmpty()){
            JOptionPane.showMessageDialog(this, "Kategori Dokumen Harus diisi");
          txtKategori.requestFocus();
        }else if(lok.isEmpty()){
            JOptionPane.showMessageDialog(this, "Lokasi Dokumen Harus diisi");
          txtLokasi.requestFocus();
        }else if(des.isEmpty()){
            JOptionPane.showMessageDialog(this, "Deskripsi Harus diisi");
          txtDes.requestFocus();
        }else if(tgl.isEmpty()){
            JOptionPane.showMessageDialog(this, "Tanggal Harus diisi");
          txtTanggal.requestFocus();
        }else{
            try {
                Connection c = Koneksi.MySQL();
                Statement st = c.createStatement();
                String query = "UPDATE data_arsip set kode_dokumen='"+kode+"', nama_dokumen='"+nama+"', kategori='"+kategori+"',"
                      + " lokasi='"+lok+"', deskripsi='"+des+"', "
                      + "tanggal='"+tgl+"'"
                      + " WHERE kode_dokumen="+arsip.getKode()+"";
                
              st.executeUpdate(query);
              JOptionPane.showMessageDialog(this, "Data Telah DiUbah!!!");
              Home.addComp(new Arsip_Dokumen());
                      
          } catch (SQLException e) {
              JOptionPane.showMessageDialog(this, e.getMessage());
              
          }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        Arsip_Dokumen d = new Arsip_Dokumen();
        this.setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        file = f.getAbsolutePath();
        txtLokasi.setText(file);
    }//GEN-LAST:event_btnUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtKategori;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
